<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Create categories
        $categories = [
            [
                'name' => 'Bouquets',
                'slug' => 'bouquets',
                'description' => 'Hand-tied bouquets for every occasion.',
                'image' => 'assets/images/bouquets/bouqet.jpeg',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Standing Flowers',
                'slug' => 'standing-flowers',
                'description' => 'Tall floral displays for celebrations and ceremonies.',
                'image' => 'assets/images/standing-flowers/standingbunga.jpeg',
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Bloom Box',
                'slug' => 'bloom-box',
                'description' => 'Curated gift boxes with seasonal blooms.',
                'image' => 'assets/images/bloom-box/blumbox.jpg',
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'Flowers',
                'slug' => 'flowers',
                'description' => 'Fresh cut flowers, ready to arrange.',
                'image' => 'assets/images/flowers/bunga.jpeg',
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'name' => 'Accessories',
                'slug' => 'accessories',
                'description' => 'Vases, ribbons, and floral accessories.',
                'image' => 'assets/images/accessories/default.png',
                'sort_order' => 5,
                'is_active' => true,
            ],
        ];

        foreach ($categories as $categoryData) {
            Category::create($categoryData);
        }

        // Create sample products with all available images
        $products = [
            // Bouquets
            [
                'category_id' => 1,
                'name' => 'Romantic Rose Bouquet',
                'slug' => 'romantic-rose-bouquet',
                'description' => 'A romantic rose bouquet with soft pastel petals.',
                'details' => 'Beautiful arrangement of 24 premium roses with premium greens and eucalyptus leaves.',
                'price' => 250000,
                'image' => 'assets/images/bouquets/bouqets1.jpeg',
                'stock' => 50,
                'is_featured' => true,
                'status' => 'active',
            ],
            [
                'category_id' => 1,
                'name' => 'Classic Bouquet Collection',
                'slug' => 'classic-bouquet-collection',
                'description' => 'Classic and elegant bouquet for any occasion.',
                'details' => 'Hand-crafted bouquet with mixed seasonal flowers.',
                'price' => 220000,
                'image' => 'assets/images/bouquets/bouqet.jpeg',
                'stock' => 55,
                'is_featured' => true,
                'status' => 'active',
            ],
            [
                'category_id' => 1,
                'name' => 'Premium Bouquet Selection',
                'slug' => 'premium-bouquet-selection',
                'description' => 'Premium selection of the finest flowers.',
                'details' => 'Luxurious bouquet arrangement with rare blooms.',
                'price' => 350000,
                'image' => 'assets/images/bouquets/bouqets.jpeg',
                'stock' => 35,
                'is_featured' => false,
                'status' => 'active',
            ],
            [
                'category_id' => 1,
                'name' => 'Exclusive Bouquet Design',
                'slug' => 'exclusive-bouquet-design',
                'description' => 'Exclusive limited edition bouquet design.',
                'details' => 'One-of-a-kind arrangement with premium flowers.',
                'price' => 450000,
                'image' => 'assets/images/bouquets/bouqetsss.jpeg',
                'stock' => 20,
                'is_featured' => true,
                'status' => 'active',
            ],

            // Standing Flowers
            [
                'category_id' => 2,
                'name' => 'Royal Standing Arrangement',
                'slug' => 'royal-standing-arrangement',
                'description' => 'An elegant standing flower arrangement for special events.',
                'details' => 'Tall standing arrangement with mixed fresh flowers and exotic blooms.',
                'price' => 400000,
                'image' => 'assets/images/standing-flowers/standingbunga2.jpeg',
                'stock' => 30,
                'is_featured' => true,
                'status' => 'active',
            ],
            [
                'category_id' => 2,
                'name' => 'Grand Standing Display',
                'slug' => 'grand-standing-display',
                'description' => 'Impressive grand standing flower display.',
                'details' => 'Large statement piece for ceremonies and events.',
                'price' => 550000,
                'image' => 'assets/images/standing-flowers/standingbunga.jpeg',
                'stock' => 25,
                'is_featured' => true,
                'status' => 'active',
            ],
            [
                'category_id' => 2,
                'name' => 'Elegant Standing Arrangement',
                'slug' => 'elegant-standing-arrangement',
                'description' => 'Elegant and refined standing arrangement.',
                'details' => 'Perfect for corporate events and special occasions.',
                'price' => 380000,
                'image' => 'assets/images/standing-flowers/standingbunga3.jpeg',
                'stock' => 28,
                'is_featured' => false,
                'status' => 'active',
            ],
            [
                'category_id' => 2,
                'name' => 'Deluxe Standing Arrangement',
                'slug' => 'deluxe-standing-arrangement',
                'description' => 'Deluxe standing arrangement with premium selection.',
                'details' => 'Luxurious display with rare and exotic flowers.',
                'price' => 600000,
                'image' => 'assets/images/standing-flowers/standingbunga5.jpeg',
                'stock' => 22,
                'is_featured' => true,
                'status' => 'active',
            ],
            [
                'category_id' => 2,
                'name' => 'Modern Standing Design',
                'slug' => 'modern-standing-design',
                'description' => 'Modern and contemporary standing flower design.',
                'details' => 'Contemporary arrangement for modern aesthetics.',
                'price' => 420000,
                'image' => 'assets/images/standing-flowers/standingbunga6.jpeg',
                'stock' => 32,
                'is_featured' => false,
                'status' => 'active',
            ],

            // Bloom Box
            [
                'category_id' => 3,
                'name' => 'Celebration Bloom Box',
                'slug' => 'celebration-bloom-box',
                'description' => 'Beautiful bloom box with seasonal fresh flowers.',
                'details' => 'Premium gift box containing assorted fresh seasonal flowers.',
                'price' => 180000,
                'image' => 'assets/images/bloom-box/box.jpeg',
                'stock' => 40,
                'is_featured' => true,
                'status' => 'active',
            ],
            [
                'category_id' => 3,
                'name' => 'Premium Bloom Box',
                'slug' => 'premium-bloom-box',
                'description' => 'Premium bloom box with luxury flowers.',
                'details' => 'Elegant gift box with carefully selected premium blooms.',
                'price' => 250000,
                'image' => 'assets/images/bloom-box/blumbox.jpg',
                'stock' => 35,
                'is_featured' => true,
                'status' => 'active',
            ],
            [
                'category_id' => 3,
                'name' => 'Deluxe Bloom Box',
                'slug' => 'deluxe-bloom-box',
                'description' => 'Deluxe bloom box with exclusive flowers.',
                'details' => 'Limited edition box with rare flower selection.',
                'price' => 320000,
                'image' => 'assets/images/bloom-box/blumbox1.jpg',
                'stock' => 28,
                'is_featured' => false,
                'status' => 'active',
            ],
            [
                'category_id' => 3,
                'name' => 'Luxury Bloom Box',
                'slug' => 'luxury-bloom-box',
                'description' => 'Luxury bloom box with premium arrangement.',
                'details' => 'Exquisite box arrangement for special moments.',
                'price' => 280000,
                'image' => 'assets/images/bloom-box/box12.jpeg',
                'stock' => 30,
                'is_featured' => false,
                'status' => 'active',
            ],
            [
                'category_id' => 3,
                'name' => 'Royal Bloom Box',
                'slug' => 'royal-bloom-box',
                'description' => 'Royal bloom box with premium selection.',
                'details' => 'Regal box arrangement with finest flowers.',
                'price' => 350000,
                'image' => 'assets/images/bloom-box/boxx.jpeg',
                'stock' => 25,
                'is_featured' => true,
                'status' => 'active',
            ],

            // Flowers
            [
                'category_id' => 4,
                'name' => 'Signature Floral Bundle',
                'slug' => 'signature-floral-bundle',
                'description' => 'Loose fresh flowers ready for custom arrangements.',
                'details' => 'Bundle of fresh cut flowers perfect for DIY arrangements.',
                'price' => 120000,
                'image' => 'assets/images/flowers/bunga12.jpeg',
                'stock' => 60,
                'is_featured' => false,
                'status' => 'active',
            ],
            [
                'category_id' => 4,
                'name' => 'Garden Bloom Set',
                'slug' => 'garden-bloom-set',
                'description' => 'Assorted garden flowers with lush greenery.',
                'details' => 'Fresh garden flowers perfect for spring arrangements.',
                'price' => 135000,
                'image' => 'assets/images/flowers/bunga23.jpeg',
                'stock' => 45,
                'is_featured' => false,
                'status' => 'active',
            ],
            [
                'category_id' => 4,
                'name' => 'Premium Fresh Flowers',
                'slug' => 'premium-fresh-flowers',
                'description' => 'Premium fresh cut flowers selection.',
                'details' => 'High quality cut flowers sourced from best farms.',
                'price' => 180000,
                'image' => 'assets/images/flowers/bunga.jpeg',
                'stock' => 50,
                'is_featured' => true,
                'status' => 'active',
            ],
            [
                'category_id' => 4,
                'name' => 'Exotic Flower Collection',
                'slug' => 'exotic-flower-collection',
                'description' => 'Exotic flowers from around the world.',
                'details' => 'Rare and exotic flowers for unique arrangements.',
                'price' => 220000,
                'image' => 'assets/images/flowers/bunga3.jpeg',
                'stock' => 35,
                'is_featured' => true,
                'status' => 'active',
            ],
            [
                'category_id' => 4,
                'name' => 'Seasonal Flower Mix',
                'slug' => 'seasonal-flower-mix',
                'description' => 'Mix of seasonal flowers available now.',
                'details' => 'Fresh seasonal selection changed regularly.',
                'price' => 155000,
                'image' => 'assets/images/flowers/bunga5.jpeg',
                'stock' => 55,
                'is_featured' => false,
                'status' => 'active',
            ],
            [
                'category_id' => 4,
                'name' => 'Classic Flower Bundle',
                'slug' => 'classic-flower-bundle',
                'description' => 'Classic flowers bundle for any occasion.',
                'details' => 'Traditional flowers always in demand.',
                'price' => 125000,
                'image' => 'assets/images/flowers/bunga21.jpeg',
                'stock' => 65,
                'is_featured' => false,
                'status' => 'active',
            ],

            // Accessories
            [
                'category_id' => 5,
                'name' => 'Gift Box & Ribbon Kit',
                'slug' => 'gift-box-ribbon-kit',
                'description' => 'Gift packaging kit with ribbons and decorative accents.',
                'details' => 'Complete gift wrapping solution with premium packaging materials.',
                'price' => 65000,
                'image' => 'assets/images/accessories/lainya.jpeg',
                'stock' => 100,
                'is_featured' => false,
                'status' => 'active',
            ],
            [
                'category_id' => 5,
                'name' => 'Premium Accessories Pack',
                'slug' => 'premium-accessories-pack',
                'description' => 'Premium floral accessories and decorations.',
                'details' => 'Quality accessories for flower arrangements.',
                'price' => 95000,
                'image' => 'assets/images/accessories/lainya1.jpeg',
                'stock' => 80,
                'is_featured' => false,
                'status' => 'active',
            ],
            [
                'category_id' => 5,
                'name' => 'Deluxe Accessory Collection',
                'slug' => 'deluxe-accessory-collection',
                'description' => 'Deluxe collection of floral accessories.',
                'details' => 'Premium vases, ribbons, and decorative items.',
                'price' => 150000,
                'image' => 'assets/images/accessories/lainya2.jpeg',
                'stock' => 60,
                'is_featured' => true,
                'status' => 'active',
            ],
        ];

        foreach ($products as $productData) {
            Product::create($productData);
        }
    }
}
